### PR TITLE
v2.0.0 release

### PR DESCRIPTION
**Pull request by Raboo**
### Description

Release v1.2.0.
The Architectures commit changes behavior a bit. So does is this still a 1.x release or should it be a 2.x release?

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by Xorima** [comment]
If you have changed a property name it should be a 2.0.0 release with an upgrading.md

**Comment by Raboo** [comment]
https://github.com/sous-chefs/aptly/commit/84b90bf4bc7a0a1cbe31160298284fd81c786c73
Property name has not changed.
the 'new' architectures was changed to match other places where we have 'architectures' (i.e. changing from string to array).
And chef doesn't have a explicit default anymore (aptly still defaults to amd64 when no architecture is set). And this so chef won't override the default architecture set in the aptly config file (as to not  render the architecture option useless in the config file).

**Comment by Xorima** [comment]
Changing the type is still a major change as you cannot just bump to this new version, you need to make changes to your codebase

**Comment by Raboo** [comment]
Alright, sounds reasonable, I've fixed it now.

**Pull request merged**
